export const products = [
  {
    id: 1,
    name: "Jacquard Zebra Curtains",
    category: "Jacquard Zebra",
    price: 4500,
    oldPrice: 5500,
    rating: 4.8,
    reviews: 124,
    badge: "New",
    sale: false,
    image: "/curtains/jacquard.webp",
    description:
      "Elegant jacquard-woven zebra curtains with a bold alternating stripe pattern. The dense weave provides excellent light filtering while adding a luxurious texture to any room.",
    tags: ["Light Filtering", "Woven Texture", "Living Room"],
    colors: ["#C8B8A0", "#8A7A68", "#E8D8C0"],
    specs: {
      Width: "140cm",
      Type: "Jacquard Zebra",
      "Mount Type": "Rod Pocket",
      Origin: "Turkey",
    },
  },
  {
    id: 2,
    name: "Lamis Magic Sheer",
    category: "Lamis Magic",
    price: 6200,
    oldPrice: 7800,
    rating: 4.9,
    reviews: 238,
    badge: "Bestseller",
    sale: true,
    image: "/curtains/lamis.webp",
    description:
      "The Lamis Magic collection delivers a soft, diffused glow through its sheer double-layer fabric. Effortlessly transitions between open and semi-sheer looks with a smooth glide system.",
    tags: ["Sheer", "Double Layer", "Gift-worthy"],
    colors: ["#F0EAD8", "#D4C8B0", "#B8A898"],
    specs: {
      Width: "200cm",
      Type: "Sheer Blind",
      "Mount Type": "Ceiling Track",
      Origin: "Belgium",
    },
  },
  {
    id: 3,
    name: "Folded Roller Curtain",
    category: "Folded Roller Curtain",
    price: 2800,
    oldPrice: null,
    rating: 4.7,
    reviews: 89,
    badge: null,
    sale: false,
    image: "/curtains/roller.webp",
    description:
      "A modern folded roller curtain with clean lines and a soft cascade effect. Ideal for minimalist interiors seeking structured elegance and precise light control.",
    tags: ["Roller", "Minimalist", "Easy Install"],
    colors: ["#E8E0D4", "#C0B8B0"],
    specs: {
      Width: "120cm",
      Type: "Roller Blind",
      "Mount Type": "Top-down",
      Origin: "Poland",
    },
  },
  {
    id: 4,
    name: "Sierra Magic Zebra",
    category: "Sierra Magic Zebra Curtains",
    price: 3400,
    oldPrice: 4200,
    rating: 4.6,
    reviews: 67,
    badge: "Sale",
    sale: true,
    image: "/curtains/zebra.avif",
    description:
      "Sierra Magic Zebra curtains combine alternating sheer and opaque bands for versatile privacy and light control. A bestseller for modern bedrooms and living spaces.",
    tags: ["Zebra Blind", "Privacy Control", "Multi-use"],
    colors: ["#B8C4C8", "#8098A0", "#D8E0E4"],
    specs: {
      Width: "160cm",
      Type: "Zebra Blind",
      "Mount Type": "Cassette",
      Origin: "South Korea",
    },
  },
  {
    id: 5,
    name: "Single Line Semi Blackout",
    category: "Single Line Semi Blackout",
    price: 1950,
    oldPrice: null,
    rating: 4.5,
    reviews: 43,
    badge: "New",
    sale: false,
    image: "/curtains/blackout.jpg",
    description:
      "A sleek single-line semi blackout blind that blocks up to 85% of incoming light. Perfect for bedrooms, nurseries, or home offices requiring reduced glare without full darkness.",
    tags: ["Semi Blackout", "Glare Control", "Bedroom"],
    colors: ["#686460", "#A09890", "#2C2A28"],
    specs: {
      Width: "180cm",
      Type: "Semi Blackout",
      "Mount Type": "Wall Mount",
      Origin: "China",
    },
  },
  {
    id: 6,
    name: "B 300 Series Blind",
    category: "B 300 Series",
    price: 1600,
    oldPrice: 2000,
    rating: 4.4,
    reviews: 55,
    badge: "Sale",
    sale: true,
    image: "/curtains/300.jpeg",
    description:
      "The B 300 Series offers a reliable, clean-look roller blind in a range of neutral tones. Built with a durable mechanism for daily use in kitchens, bathrooms, and offices.",
    tags: ["Durable", "Neutral Tones", "Office Friendly"],
    colors: ["#D8D0C8", "#B0A898", "#F0E8E0"],
    specs: {
      Width: "100cm",
      Type: "Roller Blind",
      "Mount Type": "Inside Mount",
      Origin: "Germany",
    },
  },
  {
    id: 7,
    name: "Galaxy Zebra Curtains",
    category: "Galaxy Zebra Curtains",
    price: 5100,
    oldPrice: null,
    rating: 4.9,
    reviews: 182,
    badge: "Bestseller",
    sale: false,
    image: "/curtains/galaxy.webp",
    description:
      "Galaxy Zebra curtains feature a deep, lustrous fabric with fine alternating bands that create a mesmerising depth of texture. Adds a statement focal point to any window.",
    tags: ["Statement", "Deep Texture", "100% Premium"],
    colors: ["#3A3850", "#5A5878", "#8880A8"],
    specs: {
      Width: "200cm",
      Type: "Zebra Blind",
      "Mount Type": "Cassette",
      Origin: "Italy",
    },
  },
  {
    id: 8,
    name: "Olive Shade Sweet Magic",
    category: "Olive Shade | Sweet Magic",
    price: 1200,
    oldPrice: 1500,
    rating: 4.3,
    reviews: 31,
    badge: null,
    sale: true,
    image: "/curtains/olive.jpg",
    description:
      "A warm olive-toned sheer blind with a gentle diffusing effect. The Sweet Magic finish softens natural light beautifully, creating a cosy, earthy ambiance in living rooms and dining areas.",
    tags: ["Olive", "Earthy", "Sheer Diffuse"],
    colors: ["#7A8A60", "#9AAA78", "#B8C898"],
    specs: {
      Width: "140cm",
      Type: "Sheer Blind",
      "Mount Type": "Rod Pocket",
      Origin: "Nepal",
    },
  },
  {
    id: 9,
    name: "Souvenir Curtains",
    category: "Souvenir Curtains",
    price: 3800,
    oldPrice: 4600,
    rating: 4.7,
    reviews: 104,
    badge: "Sale",
    sale: true,
    image: "/curtains/sov.webp",
    description:
      "Souvenir Curtains bring classic drapery elegance to contemporary interiors. A rich, flowing fabric with subtle patterning that works effortlessly in formal and casual rooms alike.",
    tags: ["Classic", "Flowing Fabric", "Patterned"],
    colors: ["#C8A880", "#A88860", "#E8C8A0"],
    specs: {
      Width: "250cm",
      Type: "Drape Curtain",
      "Mount Type": "Eyelet",
      Origin: "France",
    },
  },
  {
    id: 10,
    name: "Circle Roller Curtains",
    category: "Circle Roller Curtains",
    price: 2200,
    oldPrice: 2800,
    rating: 4.6,
    reviews: 76,
    badge: "New",
    sale: false,
    image: "/curtains/circle.webp",
    description:
      "Circle Roller Curtains feature a distinctive circular geometric weave for a modern, textural look. Provides excellent privacy with a semi-opaque finish that still allows soft light through.",
    tags: ["Geometric", "Semi-Opaque", "Modern"],
    colors: ["#E0D8D0", "#C8C0B8", "#A8A098"],
    specs: {
      Width: "150cm",
      Type: "Roller Blind",
      "Mount Type": "Top-down",
      Origin: "Turkey",
    },
  },
];
