export const products = [
  {
    id: 1,
    name: "Jo Malone Cologne",
    category: "Body Cologne",
    price: 4500,
    oldPrice: 5500,
    rating: 4.8,
    reviews: 124,
    badge: "New",
    sale: false,
    image:
      "https://images.unsplash.com/photo-1541643600914-78b084683702?w=400&q=80",
    description:
      "A fresh and elegant cologne crafted from the finest botanicals. Light, airy, and long-lasting — perfect for everyday wear.",
    tags: ["Organic", "Long-lasting", "Vegan"],
    colors: ["#D4A86A", "#8B6F47", "#C4B8A0"],
    specs: {
      Volume: "100ml",
      Type: "Eau de Cologne",
      "Shelf Life": "36 months",
      Origin: "UK",
    },
  },
  {
    id: 2,
    name: "Eau de Parfume",
    category: "Rose Perfume",
    price: 6200,
    oldPrice: 7800,
    rating: 4.9,
    reviews: 238,
    badge: "Bestseller",
    sale: true,
    image:
      "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=400&q=80",
    description:
      "An intoxicating blend of Bulgarian rose and warm musk. A timeless scent that lingers beautifully through the day.",
    tags: ["Rose", "Musk", "Luxury", "Gift-worthy"],
    colors: ["#E8B4A0", "#D4757A", "#F0C8B8"],
    specs: {
      Volume: "50ml",
      Type: "Eau de Parfum",
      "Shelf Life": "48 months",
      Origin: "France",
    },
  },
  {
    id: 3,
    name: "Coco Oil Organic",
    category: "Body Oil Cleanser",
    price: 2800,
    oldPrice: null,
    rating: 4.7,
    reviews: 89,
    badge: null,
    sale: false,
    image:
      "https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=400&q=80",
    description:
      "Pure cold-pressed coconut oil enriched with vitamin E. Deeply nourishes and cleanses skin without stripping natural oils.",
    tags: ["Cold-pressed", "Vitamin E", "Cruelty-free"],
    colors: ["#F5F0E8", "#E8DDD0"],
    specs: {
      Volume: "200ml",
      Type: "Body Oil",
      "Shelf Life": "24 months",
      Origin: "Nepal",
    },
  },
  {
    id: 4,
    name: "Argan Serum",
    category: "Hair & Skin Oil",
    price: 3400,
    oldPrice: 4200,
    rating: 4.6,
    reviews: 67,
    badge: "Sale",
    sale: true,
    image:
      "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400&q=80",
    description:
      "Lightweight Moroccan argan oil serum that repairs, softens, and adds brilliant shine to hair and skin.",
    tags: ["Argan", "Repair", "Lightweight", "Multi-use"],
    colors: ["#C09060", "#D4A870", "#E8C89A"],
    specs: {
      Volume: "50ml",
      Type: "Serum",
      "Shelf Life": "30 months",
      Origin: "Morocco",
    },
  },
  {
    id: 5,
    name: "Green Tea Toner",
    category: "Facial Toner",
    price: 1950,
    oldPrice: null,
    rating: 4.5,
    reviews: 43,
    badge: "New",
    sale: false,
    image:
      "https://images.unsplash.com/photo-1601049676869-702ea24cfd58?w=400&q=80",
    description:
      "Antioxidant-rich green tea toner that balances skin pH, minimises pores, and leaves skin feeling refreshed and calm.",
    tags: ["Antioxidant", "Pore-minimising", "Alcohol-free"],
    colors: ["#A8C4A8", "#C8DEC8", "#6A946A"],
    specs: {
      Volume: "150ml",
      Type: "Toner",
      "Shelf Life": "18 months",
      Origin: "Japan",
    },
  },
  {
    id: 6,
    name: "Lavender Body Mist",
    category: "Body Spray",
    price: 1600,
    oldPrice: 2000,
    rating: 4.4,
    reviews: 55,
    badge: "Sale",
    sale: true,
    image:
      "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=400&q=80",
    description:
      "A calming lavender body mist that soothes the senses and keeps skin lightly scented and hydrated all day.",
    tags: ["Lavender", "Hydrating", "Calming"],
    colors: ["#C8B8D8", "#9A80B0", "#E8D8F0"],
    specs: {
      Volume: "250ml",
      Type: "Body Mist",
      "Shelf Life": "24 months",
      Origin: "France",
    },
  },
  {
    id: 7,
    name: "Rose Hip Face Oil",
    category: "Facial Oil",
    price: 5100,
    oldPrice: null,
    rating: 4.9,
    reviews: 182,
    badge: "Bestseller",
    sale: false,
    image:
      "https://images.unsplash.com/photo-1570194065650-d99fb4bedf0a?w=400&q=80",
    description:
      "100% pure rosehip seed oil packed with omega fatty acids and vitamin A. Visibly reduces scars and evens skin tone.",
    tags: ["Vitamin A", "Scar repair", "100% Pure"],
    colors: ["#E8908A", "#D4706A", "#F0B8B0"],
    specs: {
      Volume: "30ml",
      Type: "Facial Oil",
      "Shelf Life": "12 months",
      Origin: "Chile",
    },
  },
  {
    id: 8,
    name: "Charcoal Face Wash",
    category: "Cleanser",
    price: 1200,
    oldPrice: 1500,
    rating: 4.3,
    reviews: 31,
    badge: null,
    sale: true,
    image:
      "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400&q=80",
    description:
      "Deep-cleansing activated charcoal face wash that draws out impurities, controls oil, and leaves skin feeling thoroughly clean.",
    tags: ["Activated Charcoal", "Deep Cleanse", "Oil Control"],
    colors: ["#444441", "#6A6A68", "#2C2C2A"],
    specs: {
      Volume: "100ml",
      Type: "Face Wash",
      "Shelf Life": "24 months",
      Origin: "India",
    },
  },
];
